### ISSUE TITLE
Configuration after Update not working anymore

### ISSUE THREAD

**Issue by krayzie0x10** [nextcloud/files_accesscontrol#155]
Hello,

i've upgraded from 16.X to 17.05. I've also updated all apps. 

The issue is that externals without account, can not upload anything anymore? That worked befor the update. Now, everything seems to be successful. The file is listed but when you try to open the uploaded file: "Error - Not found". 

Log only says: AV Ok and after that you get that webdav / not found exeption when you try to open the file.

I've reconfigured everything, reinstalled the app, try different configurations but i can not get it to work anymore … File Drop is not working with the Access controll anymore.

Why is same configuration that worked with 1.6.0 not working with 1.7.0?
![accesscontroll_rules](https://user-images.githubusercontent.com/39626044/79743099-450fe980-8304-11ea-8801-d864e3e56201.png)
Where can i find detailed Information why the Access controll is denying the file?

Ok, lets make it simple. I only want all my users to be able to make new Directorys and only PDF-Files are allowed on the server. 

So my configuration Looks like this:
![accesscontroll_rules_ez](https://user-images.githubusercontent.com/39626044/79747011-3d077800-830b-11ea-9486-4db183148773.png)

Right?

Now, If i upload a file via file-drop, the file ist listed but when i try to Access it, i get a
![error](https://user-images.githubusercontent.com/39626044/79747346-ca4acc80-830b-11ea-9386-352349e2cb7b.png)

Can someone explaine this?

Best regards

**Comment by krayzie85** [comment]
Update: when i initiate a rescan, the file is suddenly accesible!?

**Comment by krayzie85** [comment]
When i disable the access Control app and rescan all files, i can suddenly access the file …

**Comment by nickvergessen** [comment]
There were quite some changes in Nextcloud 18 regarding this.
Do you mind to check out if it works there?

**Comment by ClCfe** [comment]
Hello,

i have a similar problem with nextcloud 18.0.4 and file access control 1.8.1
I block mimetype="application/octet-stream"
When you upload a file, the FileMimeType check doesn't work
and it seems that it always returns "application/octet-stream"
I dunno if it is because you only want to trust a mime type based on his content (so must exists on filesystem)
or if you don't call workflowengine/lib/Check/FileMimeType.php->detectPath() properly

as a work around I thought to user Filename check, but you can't select a regexp match on the rule configurator
(I think workflowengine/lib/Check/AbstractStringCheck.php supports regexp)

**Comment by krayzie0x10** [comment]
Ive made the update but the Problems remain. As you mentioned, the update provided quite some changes. Should i open a new thread or keep it here?
