### ISSUE TITLE
Completely block user out of folder

### ISSUE THREAD

**Issue by alve89** [nextcloud/files_accesscontrol#46]
**My setting:**

Folder folder01 has the hidden tag hiddenTag01.
The rules within the app are set that users of group GroupA can't access folders / files with tag hiddenTag01.

With this app and the system tags I thought it was possible to block a user out of a folder. Unfortunately the user is still allowed to access the folder and see the listed files (without their content) within, sometimes even the preview within the thumbnail. I think that's not the best solution. 

Was it possible to restrict the access to the folder completely so the user can't even access it?
Or, a great optional setting: Hide restricted folders / files for the user.

**Comment by nickvergessen** [comment]
Previews only happen when the browser already cached them, this is not avoidable.
Other than that this file listing is not possible to block.
This is also stated in the docs:
https://docs.nextcloud.com/server/10/admin_manual/configuration_files/files_access_control.html#denied-access

The problem is, hiding individual folders/files inside a folder breaks pagination etc. So not really something that is easily solvable. So instead of bringing in a "half working block listing" we decided to not try this, so the things that work work all the time and not "sometimes".
