### ISSUE TITLE
Fatal messages in nextcloud.log while working as intended

### ISSUE THREAD

**Issue by Perry2493** [nextcloud/files_accesscontrol#93]
Hi, 
not sure if its a bug or intended.

We set up FileAccessControl, so only clients with IP-Addresses from our internal IP-Range can access files, while everyone else will get locked out. 
Only Files and Directories with a special tag can be accessed from external IP's too.

Everything works like we configured it..

But every time someone with an external IP tries to open an file without tag, he get's an error-message that this operation is not allowed and we get the following entry in nextcloud.log:
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions

Is it necessary to have an Fatal-Error here?
Since it's fatal i would guess something goes really wrong - but in fact everything is working as expected...

Maybe something to think about?

Thank you
### Steps to reproduce
1. Set up FileAccessControl with "Request remote address", "does not match IPv4" and your IP-Range
2. Try to access file from IP-Address outside of specified IP-Range

### Expected behaviour
Maybe just an "Info" or an "Warning" in nextcloud.log

### Actual behaviour
"Fatal" in nextcloud.log

### Server configuration
**Operating system**:
Ubuntu 16.04.4 LTS

**Web server:**
apache2 2.4.18

**Database:**
mariadb10 10.0.34

**PHP version:**
php7 7.0.25

**Nextcloud version:** (see Nextcloud admin page)
NC12.0.5

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.1
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.2.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - announcementcenter
  - files_external
  - groupfolders
  - user_external

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "ocmh2lhz0ngx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "NC-FQDN",
            "NC-Server.domain.xx",
            "IP",
        ],
        "trusted_proxies": [
            "Proxy-IP"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "\/mnt\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/server.domain.xx",
        "enable_previews": false,
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "activity_expire_days": 180,
        "preview_max_x": "960",
        "preview_max_y": "720",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud.log",
        "maintenance": false,
        "singleuser": true,
        "updater.release.channel": "production",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "domain.xx",
        "mail_smtphost": "SMTP-IP",
        "mail_smtpport": "25",
        "theme": "",
        "skeletondirectory": "",
        "filesystem_check_changes": 0
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS-Share from an NetApp

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes - ActiveDirectory

### Client configuration
**Browser:**
Chrome, Firefox, Edge

**Operating system:**
Windows10 and Mobile devices

#### Nextcloud log
{"reqId":"NYNkaFj3A3PkwvZ8WVQ8","level":4,"time":"2018-03-08T14:57:59+00:00","remoteAddr":"remote-IP","user":"username","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/username","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"No read permissions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/TagsPlugin.php(222): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\TagsPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1059): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(981): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('username', Array, 1)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":254}","userAgent":"Mozilla\/5.0 (Linux; Android 7.0; VTR-L29 Build\/HUAWEIVTR-L29) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.109 Mobile Safari\/537.36","version":"12.0.5.3"}

**Comment by nickvergessen** [comment]
Well that is actually a bug in the tagging component, but I will keep the issue here, since it's only triggered with this app.

**Comment by RuudschMaHinda** [comment]
Getting the Fatal log entry as well when doing this:
Tag a folder to not be downloaded by a Desktop-Client.
Desktop-Client then tries to download the folder.
Fatal error in Log files, since access is forbidden.

`{"reqId":"CM4yessXhHkUv59pVw6u","level":4,"time":"2019-06-27T17:58:23+02:00","remoteAddr":"192.168.2.169","user":"username","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/username/tagged-folder","message":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\Forbidden","Message":"No read permissions","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":195,"function":"getChildren","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":899,"function":"getChildren","class":"Sabre\\DAV\\Tree","type":"->","args":["files/username/Haus Steinstraße - Team/Archiv"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":978,"function":"generatePathNodes","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/username/Haus Steinstraße - Team/Archiv",["{DAV:}resourcetype","{DAV:}getlastmodified","{DAV:}getcontentlength","{DAV:}getetag","{http://owncloud.org/ns}id","{http://owncloud.org/ns}downloadURL","{http://owncloud.org/ns}dDC","{http://owncloud.org/ns}permissions"],1]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://my-cloud.tld/remote.php/dav/files/username/tagged-folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https://my-cloud.tld/remote.php/dav/files/username/tagged-folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https://my-cloud.tld/remote.php/dav/files/username/tagged-folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://my-cloud.tld/remote.php/dav/files/username/tagged-folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":163,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":263,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh) mirall/2.3.3 (build 84) (Nextcloud)","version":"16.0.1.1","id":"5d15685f33ccb"}`

**Comment by nickvergessen** [comment]
The reported version is EOL. If it still happens on a newer version feel free to create a new report.
